root: true

plugins:
    - eslint-plugin
    - node
extends:
    - "./packages/eslint-config-eslint/default.yml"
    - "plugin:node/recommended"
    - "plugin:eslint-plugin/recommended"
rules:
    eslint-plugin/consistent-output: "error"
    eslint-plugin/prefer-placeholders: "error"
    eslint-plugin/report-message-format: ["error", '[^a-z].*\.$']
