root: true

plugins:
    - eslint-plugin
    - node
extends:
    - "./packages/eslint-config-eslint/default.yml"
    - "plugin:node/recommended"
    - "plugin:eslint-plugin/recommended"
rules:
    eslint-plugin/consistent-output: "error"
    eslint-plugin/no-deprecated-context-methods: "error"
    eslint-plugin/prefer-output-null: "error"
    eslint-plugin/prefer-placeholders: "error"
    eslint-plugin/report-message-format: ["error", '[^a-z].*\.$']
    eslint-plugin/test-case-property-ordering: "error"
    eslint-plugin/test-case-shorthand-strings: "error"
