default: true

# Exclusions for deliberate/widespread violations
MD002: false # First header should be a h1 header
MD010: false # Hard tabs
MD013: false # Line length
MD024: false # Multiple headers with the same content
MD026: false # Trailing punctuation in header
MD030: false # Spaces after list markers
MD033: false # Allow inline HTML
MD041: false # First line in file should be a top level header
MD046: # Code block style
    style: fenced
