trigger:
  - master

jobs:
  - template: .azure-pipelines/job.yml
    parameters:
      name: test_on_linux_node12
      displayName: Test on Node.js 12 (Linux)
      vmImage: Ubuntu-16.04
      nodeVersion: 12.x

  - template: .azure-pipelines/job.yml
    parameters:
      name: test_on_linux_node10
      displayName: Test on Node.js 10 (Linux)
      vmImage: Ubuntu-16.04
      nodeVersion: 10.x

  - template: .azure-pipelines/job.yml
    parameters:
      name: test_on_linux_node8
      displayName: Test on Node.js 8 (Linux)
      vmImage: Ubuntu-16.04
      nodeVersion: 8.x

  - template: .azure-pipelines/job.yml
    parameters:
      name: test_on_windows_node12
      displayName: Test on Node.js 12 (Windows)
      vmImage: Windows-2019
      nodeVersion: 12.x

  - template: .azure-pipelines/job.yml
    parameters:
      name: test_on_macos_node12
      displayName: Test on Node.js 12 (macOS)
      vmImage: macOS-10.14
      nodeVersion: 12.x
