// Generated by CoffeeScript 1.6.3
(function() {
  var greet;

  greet = function(message, subject) {
    if (subject == null) {
      subject = "World";
    }
    return console.log(message + " " + subject + "!");
  };

  greet("Hello");

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
