// Generated by CoffeeScript 1.6.3
(function() {
  var greet;

  greet = function(message, subject) {
    if (subject == null) {
      subject = "World";
    }
    return console.log(message + " " + subject + "!");
  };

  greet("Hello");

}).call(this);

/*
//@ sourceMappingURL=data:application/json;base64,ew0KICAidmVyc2lvbiI6IDMsDQogICJmaWxlIjogIm1haW4uanMiLA0KICAic291cmNlUm9vdCI6ICIiLA0KICAic291cmNlcyI6IFsNCiAgICAibWFpbi5jb2ZmZWUiDQogIF0sDQogICJuYW1lcyI6IFtdLA0KICAibWFwcGluZ3MiOiAiO0FBQUE7Q0FBQSxJQUFBLENBQUE7O0NBQUEsQ0FBQSxDQUFRLEVBQVIsRUFBUSxFQUFDOztHQUFtQixHQUFWO01BQ2hCO0NBQVEsRUFBUixJQUFPLElBQVA7Q0FERixFQUFROztDQUFSLENBR0EsR0FBQSxFQUFBO0NBSEEiDQp9
*/
