// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  log(function() {
    return console.log('Hello!');
  });

}).call(this);

/*
 //# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAiZmlsZSI6ICJtYWluLmpzIiwKICAic291cmNlUm9vdCI6ICIiLAogICJzb3VyY2VzIjogWwogICAgIm1haW4uY29mZmVlIgogIF0sCiAgIm5hbWVzIjogW10sCiAgIm1hcHBpbmdzIjogIjtBQUFBO0NBQUEsS0FBQSxNQUFBOztDQUFBLENBQUEsQ0FBQSxNQUFJO0NBQVcsRUFBUixJQUFPLENBQVAsR0FBQTtDQUFQLEVBQUk7Q0FBSiIKfQ==
 */
