name: "\U0001F41E Report a problem"
description: "Report an issue with ESLint or rules bundled with ESLint"
title: "Bug: (fill in)"
labels:
  - bug
  - "repro:needed"
body:
- type: markdown
  attributes:
    value: ESLint adheres to the [Open JS Foundation Code of Conduct](https://eslint.org/conduct). By opening an issue, you agree to abide by the code of conduct.
- type: textarea
  attributes:
    label: Environment
    description: |
      Please tell us about how you're running ESLint (Run `npx eslint --env-info`.)
    value: |
        Node version: 
        npm version: 
        Local ESLint version: 
        Global ESLint version: 
        Operating System:
  validations:
    required: true
- type: dropdown
  attributes:
    label: What parser are you using?
    description: |
      Please keep in mind that some problems are parser-specific.
    options:
      - "Default (Espree)"
      - "@typescript-eslint/parser"
      - "@babel/eslint-parser"
      - "vue-eslint-parser"
      - "@angular-eslint/template-parser"
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you do?
    description: |
      Please include a *minimal* reproduction case with source code, configuration file, any other information about how you're using ESLint. You can use Markdown in this field.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen?
    description: |
      You can use Markdown in this field.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    description: |
      Please copy-paste the actual ESLint output. You can use Markdown in this field.
    render: markdown
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Participation
    options:
      - label: I am willing to submit a pull request for this issue.
        required: false
