name: "\U0001F4DD Non-rule change request"
description: "Request a change that is not a bug fix, rule change, or new rule"
title: "Change Request: (fill in)"
labels:
  - enhancement
  - triage
  - core
body:
- type: markdown
  attributes:
    value: ESLint adheres to the [Open JS Foundation Code of Conduct](https://eslint.org/conduct). By opening an issue, you agree to abide by the code of conduct.
- type: input
  attributes:
    label: ESLint version
    description: |
      What version of ESLint are you currently using? (Run `eslint -v`.)
    placeholder: |
      e.g. v8.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: What problem do you want to solve?
    description: |
      Please explain your use case in as much detail as possible.
    placeholder: |
      ESLint currently...
  validations:
    required: true
- type: textarea
  attributes:
    label: What do you think is the correct solution?
    description: |
      Please explain how you'd like to change ESLint to address the problem.
    placeholder: |
      I'd like ESLint to...
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Participation
    options:
      - label: I am will to submit a pull request for this change.
        required: false
