name: concurrency
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    verify_files:
        name: Verify Files

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: Install Packages
              run: npm install

            - name: Run ESLint with concurrency
              run: npx eslint --concurrency 4
