name: stale

on:
    schedule:
        - cron: "31 22 * * *" # Runs every day at 10:31 PM UTC

permissions:
    issues: write
    pull-requests: write

jobs:
    stale:
        uses: eslint/workflows/.github/workflows/stale.yml@3030377848e4c0b9c28a271b88a5c8c57359da68 # main
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
